#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinc -I/usr/include/libxml2
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = -lxml2
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/XmlCode

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/XmlCode

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/XmlCode.o $(OBJDIR_DEBUG)/src/XMLTree.o $(OBJDIR_DEBUG)/src/XMLParser.o $(OBJDIR_DEBUG)/src/Utility.o $(OBJDIR_DEBUG)/src/Source.o $(OBJDIR_DEBUG)/src/Option.o $(OBJDIR_DEBUG)/src/Main.o $(OBJDIR_DEBUG)/src/Header.o $(OBJDIR_DEBUG)/src/Dir.o $(OBJDIR_DEBUG)/src/ClassPara.o $(OBJDIR_DEBUG)/src/ClassDetail.o $(OBJDIR_DEBUG)/src/ClassCont.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/XmlCode.o $(OBJDIR_RELEASE)/src/XMLTree.o $(OBJDIR_RELEASE)/src/XMLParser.o $(OBJDIR_RELEASE)/src/Utility.o $(OBJDIR_RELEASE)/src/Source.o $(OBJDIR_RELEASE)/src/Option.o $(OBJDIR_RELEASE)/src/Main.o $(OBJDIR_RELEASE)/src/Header.o $(OBJDIR_RELEASE)/src/Dir.o $(OBJDIR_RELEASE)/src/ClassPara.o $(OBJDIR_RELEASE)/src/ClassDetail.o $(OBJDIR_RELEASE)/src/ClassCont.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/XmlCode.o: src/XmlCode.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/XmlCode.cpp -o $(OBJDIR_DEBUG)/src/XmlCode.o

$(OBJDIR_DEBUG)/src/XMLTree.o: src/XMLTree.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/XMLTree.cpp -o $(OBJDIR_DEBUG)/src/XMLTree.o

$(OBJDIR_DEBUG)/src/XMLParser.o: src/XMLParser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/XMLParser.cpp -o $(OBJDIR_DEBUG)/src/XMLParser.o

$(OBJDIR_DEBUG)/src/Utility.o: src/Utility.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Utility.cpp -o $(OBJDIR_DEBUG)/src/Utility.o

$(OBJDIR_DEBUG)/src/Source.o: src/Source.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Source.cpp -o $(OBJDIR_DEBUG)/src/Source.o

$(OBJDIR_DEBUG)/src/Option.o: src/Option.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Option.cpp -o $(OBJDIR_DEBUG)/src/Option.o

$(OBJDIR_DEBUG)/src/Main.o: src/Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Main.cpp -o $(OBJDIR_DEBUG)/src/Main.o

$(OBJDIR_DEBUG)/src/Header.o: src/Header.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Header.cpp -o $(OBJDIR_DEBUG)/src/Header.o

$(OBJDIR_DEBUG)/src/Dir.o: src/Dir.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Dir.cpp -o $(OBJDIR_DEBUG)/src/Dir.o

$(OBJDIR_DEBUG)/src/ClassPara.o: src/ClassPara.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ClassPara.cpp -o $(OBJDIR_DEBUG)/src/ClassPara.o

$(OBJDIR_DEBUG)/src/ClassDetail.o: src/ClassDetail.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ClassDetail.cpp -o $(OBJDIR_DEBUG)/src/ClassDetail.o

$(OBJDIR_DEBUG)/src/ClassCont.o: src/ClassCont.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ClassCont.cpp -o $(OBJDIR_DEBUG)/src/ClassCont.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/XmlCode.o: src/XmlCode.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/XmlCode.cpp -o $(OBJDIR_RELEASE)/src/XmlCode.o

$(OBJDIR_RELEASE)/src/XMLTree.o: src/XMLTree.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/XMLTree.cpp -o $(OBJDIR_RELEASE)/src/XMLTree.o

$(OBJDIR_RELEASE)/src/XMLParser.o: src/XMLParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/XMLParser.cpp -o $(OBJDIR_RELEASE)/src/XMLParser.o

$(OBJDIR_RELEASE)/src/Utility.o: src/Utility.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Utility.cpp -o $(OBJDIR_RELEASE)/src/Utility.o

$(OBJDIR_RELEASE)/src/Source.o: src/Source.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Source.cpp -o $(OBJDIR_RELEASE)/src/Source.o

$(OBJDIR_RELEASE)/src/Option.o: src/Option.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Option.cpp -o $(OBJDIR_RELEASE)/src/Option.o

$(OBJDIR_RELEASE)/src/Main.o: src/Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Main.cpp -o $(OBJDIR_RELEASE)/src/Main.o

$(OBJDIR_RELEASE)/src/Header.o: src/Header.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Header.cpp -o $(OBJDIR_RELEASE)/src/Header.o

$(OBJDIR_RELEASE)/src/Dir.o: src/Dir.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Dir.cpp -o $(OBJDIR_RELEASE)/src/Dir.o

$(OBJDIR_RELEASE)/src/ClassPara.o: src/ClassPara.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ClassPara.cpp -o $(OBJDIR_RELEASE)/src/ClassPara.o

$(OBJDIR_RELEASE)/src/ClassDetail.o: src/ClassDetail.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ClassDetail.cpp -o $(OBJDIR_RELEASE)/src/ClassDetail.o

$(OBJDIR_RELEASE)/src/ClassCont.o: src/ClassCont.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ClassCont.cpp -o $(OBJDIR_RELEASE)/src/ClassCont.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

